//! Per-Turn summary rollup.
//!
//! One [`TurnSummaryRow`] per [`Turn`], in chronological order
//! (matching `Episodes.turns`).
//!
//! [`Turn`]: crate::episode::Turn

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};

use crate::analyzer::duration_ms_opt;
use crate::episode::{mode_segment::Mode, turn::TurnStatus, Episodes};

/// Summary row for one assistant turn.
///
/// One row per [`Turn`] from the source [`Episodes`]; rows are emitted in
/// the same chronological order as `episodes.turns` (`Vec`-position
/// preserved).
///
/// `tool_call_count` / `hook_call_count` / `skill_call_count` reflect the
/// back-references on `Turn.{tool,hook,skill}_calls` after the M1.4 P0
/// fix (back-refs attribute to start-time turn — see ADR-0005 D-2).
///
/// # Examples
///
/// ```
/// use agentprof_core::analyzer::{turn_summary, TurnSummaryRow};
/// use agentprof_core::episode::Episodes;
///
/// let rows: Vec<TurnSummaryRow> = turn_summary(&Episodes::new());
/// assert!(rows.is_empty());
/// ```
///
/// [`Turn`]: crate::episode::Turn
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TurnSummaryRow {
    /// `Turn.id` from the source Episodes.
    pub turn_id: String,
    /// Wall-clock start of the turn.
    pub started_at: DateTime<Utc>,
    /// Wall-clock duration if the turn closed; `None` for open turns.
    #[serde(with = "duration_ms_opt", default)]
    pub duration: Option<Duration>,
    /// Terminal status (Open / Completed / Aborted(reason)).
    pub status: TurnStatus,
    /// Model in use at turn start, when reported by the adapter.
    pub model: Option<String>,
    /// Mode active at turn start, when known.
    pub mode: Option<Mode>,
    /// Tokens generated by the assistant in this turn, when known.
    pub output_tokens: Option<u32>,
    /// Number of tool invocations attributed to this turn
    /// (per `Turn.tool_calls.len()`).
    pub tool_call_count: usize,
    /// Number of hook invocations attributed to this turn
    /// (per `Turn.hook_calls.len()`).
    pub hook_call_count: usize,
    /// Number of skill invocations attributed to this turn
    /// (per `Turn.skill_calls.len()`).
    pub skill_call_count: usize,
}

/// Compute one [`TurnSummaryRow`] per turn in `episodes.turns` order.
///
/// Pure: no I/O, no clock access. Deterministic for fixed input.
///
/// # Examples
///
/// ```
/// use agentprof_core::analyzer::turn_summary;
/// use agentprof_core::episode::Episodes;
///
/// let rows = turn_summary(&Episodes::new());
/// assert!(rows.is_empty());
/// ```
#[must_use]
pub fn turn_summary(episodes: &Episodes) -> Vec<TurnSummaryRow> {
    episodes
        .turns
        .iter()
        .map(|t| TurnSummaryRow {
            turn_id: t.id.clone(),
            started_at: t.started_at,
            duration: t.ended_at.map(|end| end - t.started_at),
            status: t.status.clone(),
            model: t.model.clone(),
            mode: t.mode.clone(),
            output_tokens: t.output_tokens,
            tool_call_count: t.tool_calls.len(),
            hook_call_count: t.hook_calls.len(),
            skill_call_count: t.skill_calls.len(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::episode::{call_ref::CallRef, turn::Turn, Episodes};
    use chrono::TimeZone;

    fn at(s: u32) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 5, 29, 0, 0, s).unwrap()
    }

    #[test]
    fn empty_episodes_produces_empty_rows() {
        let rows = turn_summary(&Episodes::new());
        assert!(rows.is_empty());
    }

    #[test]
    fn open_turn_has_none_duration_and_open_status() {
        let mut ep = Episodes::new();
        let turn = Turn::new("t1".into(), at(1));
        ep.turns.push(turn);
        let rows = turn_summary(&ep);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].turn_id, "t1");
        assert_eq!(rows[0].duration, None);
        assert_eq!(rows[0].status, TurnStatus::Open);
        assert_eq!(rows[0].tool_call_count, 0);
        assert_eq!(rows[0].hook_call_count, 0);
        assert_eq!(rows[0].skill_call_count, 0);
    }

    #[test]
    fn closed_turn_has_duration_and_status_completed_with_counts() {
        let mut ep = Episodes::new();
        let mut turn = Turn::new("t1".into(), at(1));
        turn.ended_at = Some(at(5));
        turn.status = TurnStatus::Completed;
        turn.tool_calls.push(CallRef::new("bash".into(), 0));
        turn.tool_calls.push(CallRef::new("view".into(), 0));
        turn.hook_calls.push(CallRef::new("PreToolUse".into(), 0));
        ep.turns.push(turn);
        let rows = turn_summary(&ep);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].duration, Some(Duration::seconds(4)));
        assert_eq!(rows[0].status, TurnStatus::Completed);
        assert_eq!(rows[0].tool_call_count, 2);
        assert_eq!(rows[0].hook_call_count, 1);
        assert_eq!(rows[0].skill_call_count, 0);
    }
}
