//! OTLP receiver subsystem (M2.2). Gated by the `otlp` cargo feature.
//!
//! # Modules
//!
//! - [`config`] — [`config::OtlpServerConfig`] + [`config::PartialOtlpServerConfig`]
//! - [`error`] — [`error::OtlpServerError`] / [`error::MapperError`] / [`error::RouterError`]
//! - [`pipeline`] — [`pipeline::IngestPipeline`] fan-in stub (M2.2 T2.2)
//! - [`server_grpc`] — tonic gRPC listener wiring (M2.2 T2.2)
//! - [`server_http`] — axum HTTP/protobuf listener wiring (M2.2 T3.1)
//! - [`auth`] — bearer-token interceptor + middleware (M2.2 T4.1)
//! - [`tls`] — server TLS + optional mTLS config builder (M2.2 T4.2)
//! - [`typed`] — [`typed::TypedEvent`] intermediate representation (M2.2 T5.1)
//! - [`mapper`] — OTLP wire types → [`typed::TypedEvent`] conversion (M2.2 T5.2)
//! - [`router`] — [`router::SessionRouter`] + per-session [`router::SessionBuffer`]
//!   with OOM caps + idle / shutdown flush triggers (M2.2 T6.1)
//!
//! Additional modules land in subsequent M2.2 tasks.
//!
//! The crate-private `proto` module mirrors the upstream
//! `opentelemetry::proto::*` module layout so the relative paths emitted
//! by `tonic_build` (e.g. `super::super::super::logs::v1::ResourceLogs`)
//! resolve correctly. Both [`pipeline`] and [`server_grpc`] share these
//! generated types so request / response plumbing type-checks without an
//! extra conversion layer.

pub mod auth;
pub mod config;
pub mod error;
pub mod mapper;
pub mod pipeline;
pub mod router;
pub mod server_grpc;
pub mod server_http;
pub mod tls;
pub mod typed;

pub use config::{OtlpServerConfig, PartialOtlpServerConfig};
pub use error::{MapperError, OtlpServerError, RouterError};

#[rustfmt::skip]
#[doc(hidden)]
#[allow(clippy::redundant_pub_crate)]
pub mod proto {
    //! Tonic-generated OTLP collector service stubs + prost message types.
    //!
    //! The nesting mirrors `opentelemetry::proto::*` exactly because the
    //! files generated by `tonic_build` use `super::super::super::`
    //! relative paths to refer to sibling message modules.

    pub mod opentelemetry {
        pub mod proto {
            pub mod common {
                pub mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.common.v1.rs"));
                }
            }
            pub mod resource {
                pub mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.resource.v1.rs"));
                }
            }
            pub mod logs {
                pub mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.logs.v1.rs"));
                }
            }
            pub mod metrics {
                pub mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.metrics.v1.rs"));
                }
            }
            pub mod trace {
                pub mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.trace.v1.rs"));
                }
            }
            pub mod collector {
                pub mod logs {
                    pub mod v1 {
                        #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                        include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.logs.v1.rs"));
                    }
                }
                pub mod metrics {
                    pub mod v1 {
                        #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                        include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.metrics.v1.rs"));
                    }
                }
                pub mod trace {
                    pub mod v1 {
                        #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                        include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.trace.v1.rs"));
                    }
                }
            }
        }
    }

    // Short-path re-exports used by `pipeline` and `server_grpc`.
    pub use self::opentelemetry::proto::collector::logs::v1 as logs;
    pub use self::opentelemetry::proto::collector::metrics::v1 as metrics;
    pub use self::opentelemetry::proto::collector::trace::v1 as trace;
}
