//! OTLP receiver subsystem (M2.2). Gated by the `otlp` cargo feature.
//!
//! # Modules
//!
//! - [`config`] — [`config::OtlpServerConfig`] + [`config::PartialOtlpServerConfig`]
//! - [`error`] — [`error::OtlpServerError`] / [`error::MapperError`] / [`error::RouterError`]
//! - [`pipeline`] — [`pipeline::IngestPipeline`] fan-in stub (M2.2 T2.2)
//! - [`server_grpc`] — tonic gRPC listener wiring (M2.2 T2.2)
//! - [`server_http`] — axum HTTP/protobuf listener wiring (M2.2 T3.1)
//! - [`auth`] — bearer-token interceptor + middleware (M2.2 T4.1)
//!
//! Additional modules (`tls` / `mapper` / `session_router` / `typed`)
//! land in subsequent M2.2 tasks.
//!
//! The crate-private `proto` module mirrors the upstream
//! `opentelemetry::proto::*` module layout so the relative paths emitted
//! by `tonic_build` (e.g. `super::super::super::logs::v1::ResourceLogs`)
//! resolve correctly. Both [`pipeline`] and [`server_grpc`] share these
//! generated types so request / response plumbing type-checks without an
//! extra conversion layer.

pub mod auth;
pub mod config;
pub mod error;
pub mod pipeline;
pub mod server_grpc;
pub mod server_http;

pub use config::{OtlpServerConfig, PartialOtlpServerConfig};
pub use error::{MapperError, OtlpServerError, RouterError};

#[rustfmt::skip]
#[allow(clippy::redundant_pub_crate)]
pub(crate) mod proto {
    //! Tonic-generated OTLP collector service stubs + prost message types.
    //!
    //! The nesting mirrors `opentelemetry::proto::*` exactly because the
    //! files generated by `tonic_build` use `super::super::super::`
    //! relative paths to refer to sibling message modules.

    pub(crate) mod opentelemetry {
        pub(crate) mod proto {
            pub(crate) mod common {
                pub(crate) mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.common.v1.rs"));
                }
            }
            pub(crate) mod resource {
                pub(crate) mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.resource.v1.rs"));
                }
            }
            pub(crate) mod logs {
                pub(crate) mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.logs.v1.rs"));
                }
            }
            pub(crate) mod metrics {
                pub(crate) mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.metrics.v1.rs"));
                }
            }
            pub(crate) mod trace {
                pub(crate) mod v1 {
                    #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                    include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.trace.v1.rs"));
                }
            }
            pub(crate) mod collector {
                pub(crate) mod logs {
                    pub(crate) mod v1 {
                        #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                        include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.logs.v1.rs"));
                    }
                }
                pub(crate) mod metrics {
                    pub(crate) mod v1 {
                        #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                        include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.metrics.v1.rs"));
                    }
                }
                pub(crate) mod trace {
                    pub(crate) mod v1 {
                        #![allow(missing_docs, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
                        include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.trace.v1.rs"));
                    }
                }
            }
        }
    }

    // Short-path re-exports used by `pipeline` and `server_grpc`.
    pub(crate) use self::opentelemetry::proto::collector::logs::v1 as logs;
    pub(crate) use self::opentelemetry::proto::collector::metrics::v1 as metrics;
    pub(crate) use self::opentelemetry::proto::collector::trace::v1 as trace;
}
